plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = project.mod_version

repositories {
	maven {
		name = 'henkelmax.public'
		url = 'https://maven.maxhenkel.de/repository/public'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"bcya" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	compileOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
	implementation include("javazoom:jlayer:${project.jlayer_version}")
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
